//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_III_Proyecto_final_Caja_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int ID_Factura { get; set; }
        public int Monto_total { get; set; }
        public System.DateTime fecha { get; set; }
        public int Id_reservacion { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
