//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_III_Proyecto_final_Caja_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuentas_por_cobrar> Cuentas_por_cobrar { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<Huespedes> Huespedes { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<BuscarHuesped_Result> BuscarHuesped(string nombre, string apellidos)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarHuesped_Result>("BuscarHuesped", nombreParameter, apellidosParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> LoginProcedure(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("LoginProcedure", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ObtenerDatosHabitacion_Result> ObtenerDatosHabitacion(Nullable<int> iD_Habitacion)
        {
            var iD_HabitacionParameter = iD_Habitacion.HasValue ?
                new ObjectParameter("ID_Habitacion", iD_Habitacion) :
                new ObjectParameter("ID_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDatosHabitacion_Result>("ObtenerDatosHabitacion", iD_HabitacionParameter);
        }
    
        public virtual ObjectResult<ObtenerDatosHuespedPorTelefono_Result> ObtenerDatosHuespedPorTelefono(Nullable<int> telefono)
        {
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDatosHuespedPorTelefono_Result>("ObtenerDatosHuespedPorTelefono", telefonoParameter);
        }
    
        public virtual ObjectResult<ObtenerDatosServicioPorIdHuesped_Result> ObtenerDatosServicioPorIdHuesped(Nullable<int> idHuesped)
        {
            var idHuespedParameter = idHuesped.HasValue ?
                new ObjectParameter("IdHuesped", idHuesped) :
                new ObjectParameter("IdHuesped", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDatosServicioPorIdHuesped_Result>("ObtenerDatosServicioPorIdHuesped", idHuespedParameter);
        }
    
        public virtual int ObtenerTotalPreciosServicioPorIdHuesped(Nullable<int> idHuesped, ObjectParameter totalPrecios)
        {
            var idHuespedParameter = idHuesped.HasValue ?
                new ObjectParameter("IdHuesped", idHuesped) :
                new ObjectParameter("IdHuesped", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ObtenerTotalPreciosServicioPorIdHuesped", idHuespedParameter, totalPrecios);
        }
    }
}
